## Test the algorithm

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [3]:
X = iris.data

In [4]:
y = iris.target

In [5]:
X.shape

(150, 4)

In [6]:
y.shape

(150,)

train test split

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
shuffled_indexes = np.random.permutation(len(X))
shuffled_indexes

array([ 31,  74, 145, 113, 135, 108, 116,  28,  29, 105,  95,  76,  36,
        33,  54,  24, 133,  44,  46,  61,  71,  81, 127,   7,  66, 103,
       109, 125,  92,   5, 146, 121, 149,  18,  91,  68, 104, 147,  27,
        30,  26,  52, 134,  82,  45,  25,  83,  22, 128,   2,  40,  87,
       112,  78,  60,  77,  93, 101,  13,  35,  53,  88, 114,  57, 139,
        20,  15,  72,  59, 148,  64,  96, 102,  80,  38, 119,  42,  11,
        90,  69,  67,  41,  62,  73,  39,  43, 122,  48, 129, 124,  50,
        89,  10, 118,  63, 130, 143, 120,  51,  84,  98,  85, 141, 144,
        49,  56, 131,  65,  75, 115,  55,  32, 140,  86, 132,  37,  97,
       142,  58,   3,  21, 137, 123,  47,   4, 126,  99,   8,  79,  14,
       100, 138,  16, 117,  17,   1,  34, 106,   0,   6, 110,  19,  23,
       111,  94,  70, 136,  12, 107,   9])

In [9]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [10]:
test_indexes = shuffled_indexes[:test_size]
train_indexes = shuffled_indexes[test_size:]

In [11]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [12]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [13]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [15]:
from ML.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [16]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [17]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


Test the algorithm

In [20]:
from ML.kNN import KNNClassifier

my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [21]:
y_predict

array([2, 2, 1, 2, 0, 0, 2, 0, 2, 1, 1, 0, 0, 2, 0, 2, 0, 0, 1, 2, 0, 0,
       1, 0, 1, 1, 0, 2, 1, 1])

In [22]:
y_test

array([2, 2, 1, 2, 0, 0, 2, 0, 2, 1, 1, 0, 0, 2, 0, 2, 0, 0, 1, 2, 0, 0,
       1, 0, 1, 1, 0, 2, 1, 2])

In [23]:
sum(y_predict == y_test)

29

In [24]:
sum(y_predict == y_test) / len(y_test)

0.9666666666666667

train_test_split in sklearn

In [25]:
from sklearn.model_selection import train_test_split

train_test_split

<function sklearn.model_selection._split.train_test_split(*arrays, **options)>

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [27]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [28]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
